#!/usr/bin/env bash
# ai-attribution-scrubber.sh
# Event: PreToolUse / Bash
# Blocks `git commit` whose message carries AI attribution (co-author tags,
# "Generated with", robot emoji, "AI-generated"). Exit 2 blocks; otherwise 0.
# Defensive: missing jq or unreadable input -> exit 0 (never break the flow).

set -u

# Read STDIN payload (Claude Code passes the tool call as JSON).
INPUT="$(cat 2>/dev/null || true)"
[ -z "$INPUT" ] && exit 0

# jq is required to parse the payload; if absent, do not block.
command -v jq >/dev/null 2>&1 || exit 0

COMMAND="$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null)"
[ -z "$COMMAND" ] && exit 0

# Only act on git commit invocations.
printf '%s' "$COMMAND" | grep -Eq 'git[[:space:]]+commit' || exit 0

# Look for AI attribution markers (case-insensitive). The robot emoji is a
# literal byte match so it works regardless of locale.
if printf '%s' "$COMMAND" | grep -Eiq 'co-authored-by:[[:space:]]*claude|co-authored-by:.*(anthropic|noreply@anthropic|copilot)|generated with claude|generated by claude|created by claude|written by claude|ai-generated|ai-assisted' \
   || printf '%s' "$COMMAND" | grep -q '🤖'; then
  cat >&2 <<'EOF'
Commit bloqueado: a mensagem contem atribuicao AI.
Commits devem parecer escritos por um desenvolvedor humano.
Remova linhas como "Co-authored-by: Claude", "Generated with", o emoji 🤖
ou "AI-generated" antes de commitar.
EOF
  exit 2
fi

exit 0
