#!/usr/bin/env bash
# ai-attribution-scrubber.sh
# Evento: PreToolUse / Bash
# Bloqueia `git commit` cuja mensagem contenha atribuicao de IA (tags de
# co-autor, "Generated with", emoji de robo, "AI-generated"). Exit 2 bloqueia;
# caso contrario, 0.
# Defensivo: jq ausente ou input ilegivel -> exit 0 (nunca interrompe o fluxo).

set -u

# Le o payload do STDIN (Claude Code passa a chamada da tool como JSON).
INPUT="$(cat 2>/dev/null || true)"
[ -z "$INPUT" ] && exit 0

# jq e necessario para parsear o payload; se ausente, nao bloqueia.
command -v jq >/dev/null 2>&1 || exit 0

COMMAND="$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null)"
[ -z "$COMMAND" ] && exit 0

# So atua em invocacoes de git commit.
printf '%s' "$COMMAND" | grep -Eq 'git[[:space:]]+commit' || exit 0

# Procura marcadores de atribuicao de IA (case-insensitive). O emoji de robo
# e comparado como byte literal para funcionar independente do locale.
if printf '%s' "$COMMAND" | grep -Eiq 'co-authored-by:[[:space:]]*claude|co-authored-by:.*(anthropic|noreply@anthropic|copilot)|generated with claude|generated by claude|created by claude|written by claude|ai-generated|ai-assisted' \
   || printf '%s' "$COMMAND" | grep -q '🤖'; then
  cat >&2 <<'EOF'
Commit bloqueado: a mensagem contem atribuicao AI.
Commits devem parecer escritos por um desenvolvedor humano.
Remova linhas como "Co-authored-by: Claude", "Generated with", o emoji 🤖
ou "AI-generated" antes de commitar.
EOF
  exit 2
fi

exit 0
